version: '3.7'

services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /page_for_letsencrypt/www.cloudiolab.com:/usr/share/nginx/html/www.cloudiolab.com
    secrets:
      - cloudiolab.com.fullchain.pem
      - cloudiolab.com.privkey.pem
      - cloudiolab.com.dhparam.pem
      - www.cloudiolab.com.fullchain.pem
      - www.cloudiolab.com.privkey.pem
      - www.cloudiolab.com.dhparam.pem
    configs:
      - source: mNode-nginx-01072118
        target: /etc/nginx/conf.d/default.conf
    networks:
      - cloudiolab_common_network_mNode
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == mNode]

networks:
  cloudiolab_common_network_mNode:
    external: true

secrets:
  cloudiolab.com.fullchain.pem:
    external: true
  cloudiolab.com.privkey.pem:
    external: true
  cloudiolab.com.dhparam.pem:
    external: true
  www.cloudiolab.com.fullchain.pem:
    external: true
  www.cloudiolab.com.privkey.pem:
    external: true
  www.cloudiolab.com.dhparam.pem:
    external: true

configs:
  mNode-nginx-01072118:
    file: ./nginx.conf